### ISSUE TITLE
Missing propublica-recidivism_race_0.npz

### ISSUE THREAD

**Issue by meghana-kshirsagar** [predictive-analytics-lab/ethicml-models#4]
I was trying to run the sample command provided, but don't have the dataset that it refers to. Can you please supply this data ?
I only have a CSV file of the COMPAS dataset that I obtained from elsewhere.

**Comment by tmke8** [comment]
Hi, let me try to remember how I generated these files...

**Comment by tmke8** [comment]
Sorry for the late reply. The data files are here: https://github.com/predictive-analytics-lab/tiny-comparison-framework/tree/master/data_files This was previously a private repository, but I made it public now.
